---

ntp:
  - '216.239.35.8'

timezone: Etc/UTC

ptm:
  - '"leaf-1":"swp51" -- "spine-1":"swp1"'
  - '"leaf-2":"swp51" -- "spine-1":"swp2"'
  - '"leaf-3":"swp51" -- "spine-1":"swp3"'
  - '"leaf-4":"swp51" -- "spine-1":"swp4"'
  - '"leaf-5":"swp51" -- "spine-1":"swp5"'
  - '"leaf-6":"swp51" -- "spine-1":"swp6"'
  - '"leaf-1":"swp52" -- "spine-2":"swp1"'
  - '"leaf-2":"swp52" -- "spine-2":"swp2"'
  - '"leaf-3":"swp52" -- "spine-2":"swp3"'
  - '"leaf-4":"swp52" -- "spine-2":"swp4"'
  - '"leaf-5":"swp52" -- "spine-2":"swp5"'
  - '"leaf-6":"swp52" -- "spine-2":"swp6"'
  - '"leaf-1":"swp53" -- "leaf-2":"swp53"'
  - '"leaf-1":"swp54" -- "leaf-2":"swp54"'
  - '"leaf-3":"swp53" -- "leaf-4":"swp53"'
  - '"leaf-3":"swp54" -- "leaf-4":"swp54"'
  - '"leaf-5":"swp53" -- "leaf-6":"swp53"'
  - '"leaf-5":"swp54" -- "leaf-6":"swp54"'
  - '"edge-1":"swp53" -- "edge-2":"swp53"'
  - '"edge-1":"swp54" -- "edge-2":"swp54"'
  - '"edge-1":"swp51" -- "spine-1":"swp51"'
  - '"edge-1":"swp52" -- "spine-2":"swp51"'
  - '"edge-2":"swp51" -- "spine-1":"swp52"'
  - '"edge-2":"swp52" -- "spine-2":"swp52"'
