---

interfaces:
  swp1:
    alias: downlink-leaf-1
    address: "{{ loopback }}"

  swp2:
    alias: downlink-leaf-2
    address: "{{ loopback }}"

  swp3:
    alias: downlink-leaf-3
    address: "{{ loopback }}"

  swp4:
    alias: downlink-leaf-4
    address: "{{ loopback }}"

  swp5:
    alias: downlink-leaf-5
    address: "{{ loopback }}"

  swp6:
    alias: downlink-leaf-6
    address: "{{ loopback }}"

  swp51:
    alias: downlink-edge-1
    address: "{{ loopback }}"

  swp52:
    alias: downlink-edge-1
    address: "{{ loopback }}"
