cript:
    - git clone https://github.com/berndonline/cumulus-lab-vagrant.git
    - cd cumulus-lab-vagrant/
stages:
    - validate ansible
    - staging
    - staging_rollback
    - production
    - production_rollback
validate:
    stage: validate ansible
    script:
        - bash ../linter.sh
staging:
    stage: staging
    script:
        - python ./topology_converter.py ./topology-noservers.dot -p libvirt --ansible-hostfile
        - vagrant up
        - sleep 300
        - ansible-playbook ../site.yml
        - vagrant destroy
staging_rollback:
    stage: staging_rollback
    when: on_failure
    script:
        - vagrant destroy
production:
    stage: production
    when: manual
    script:
        - vagrant up
        - sleep 300
        - ansible-playbook ../site.yml
        - vagrant destroy
    only:
        - master
production_rollback:
    stage: production_rollback
    when: on_failure
    script:
        - vagrant destroy
    only:
        - master
