before_script:
    - git clone https://github.com/berndonline/cumulus-lab-vagrant.git
    - cd cumulus-lab-vagrant/
        
stages:
    - staging
    - production
    
staging:
    stage: staging
    script:
        - vagrant up
        - sleep 300
        - ansible-playbook ../site.yml
        - vagrant destroy
        
production:
    stage: production
    script:
        - vagrant up
        - sleep 300
        - ansible-playbook ../site.yml
        - vagrant destroy
    only:
        - master
