---
stages:
    - validate ansible
    - staging
    - production
    - production_rollback
validate:
    stage: validate ansible
    script:
        - bash ./linter.sh
staging:
    before_script:
        - git clone https://github.com/berndonline/cumulus-lab-vagrant.git
        - cd cumulus-lab-vagrant/
        - python ./topology_converter.py ./topology-staging.dot
          -p libvirt --ansible-hostfile
    stage: staging
    script:
        - vagrant up
        - sleep 300
        - ansible-playbook ../site.yml
        - vagrant destroy
production:
    before_script:
        - git clone https://github.com/berndonline/cumulus-lab-vagrant.git
        - cd cumulus-lab-vagrant/
        - python ./topology_converter.py ./topology-production.dot
          -p libvirt --ansible-hostfile
    stage: production
    when: manual
    script:
        - vagrant up mgmt-1 mgmt-server
        - sleep 300
        - vagrant up
        - sleep 600
        - ansible-playbook ../site.yml
        - vagrant destroy
    only:
        - master
production_rollback:
    stage: production_rollback
    when: on_failure
    script:
        - sleep 60
    only:
        - master

