---
- hosts: all
  remote_user: cumulus
  gather_facts: no
  become: yes
  vars:
    ansible_become_pass: "CumulusLinux!"
  tasks:
    - name: fetch ports.conf
      fetch: dest=backup/{{inventory_hostname}}/ports.conf src=/etc/cumulus/ports.conf flat=yes

    - name: fetch interfaces
      fetch: dest=backup/{{inventory_hostname}}/interfaces src=/etc/network/interfaces flat=yes

    - name: copy quagga daemons file
      fetch: dest=backup/{{inventory_hostname}}/daemons src=/etc/quagga/daemons flat=yes

    - name: copy Quagga.conf
      fetch: dest=backup/{{inventory_hostname}}/Quagga.conf src=/etc/quagga/Quagga.conf flat=yes
