---

- hosts: network
  remote_user: cumulus
  gather_facts: 'no'
  become: 'yes'

  vars:
    ansible_become_pass: "CumulusLinux!"

  tasks:
    - name: fetch ports.conf
      fetch: dest=backup/{{inventory_hostname}}/ports.conf
             src=/etc/cumulus/ports.conf flat=yes

    - name: fetch interfaces
      fetch: dest=backup/{{inventory_hostname}}/interfaces
             src=/etc/network/interfaces flat=yes

    - name: fetch interfaces_config
      fetch: dest=backup/{{inventory_hostname}}/interfaces_config
             src=/etc/network/interfaces.d/interfaces_config flat=yes

    - name: copy frr daemons file
      fetch: dest=backup/{{inventory_hostname}}/daemons
             src=/etc/frr/daemons flat=yes

    - name: copy frr.conf
      fetch: dest=backup/{{inventory_hostname}}/frr.conf
             src=/etc/frr/frr.conf flat=yes
