---
- hosts: all
  remote_user: cumulus
  gather_facts: no
  become: yes

  handlers:
    - name: apply hostname
      command: hostname -F /etc/hostname

  tasks:
    - name: write hostname
      lineinfile: dest=/etc/hostname
                  regexp='^' backrefs=no
                  line='{{ inventory_hostname }}'
                  state=present
      notify: apply hostname
    - name: Remote cumulus hostname from Local DNS Resolution 
      lineinfile: dest=/etc/hosts
                  regexp='^.*  cumulus' backrefs=no
                  line='127.0.1.1  cumulus'
                  state=absent
    - name: Add Local DNS Resolution for our Hostname
      lineinfile: dest=/etc/hosts
                  regexp='^.*       {{ inventory_hostname }}' backrefs=no
                  line='127.0.1.1       {{ inventory_hostname }}'
                  state=present
      notify: apply hostname
