---

- hosts: spine leaf
  gather_facts: "False"
  user: '{{ ansible_ssh_user }}'

  tasks:
     - name: Gather Clag info in JSON
       command: netq check bgp json
       register: result
       run_once: true
       failed_when: "'ERROR' in result.stdout"

     - name: stdout string into json
       set_fact: json_output="{{result.stdout | from_json }}"
       run_once: true

     - name: output of json_output variable
       debug: var=json_output
       run_once: true

     - name: check failed bgp members
       debug: msg="Check failed bgp members"
       when: json_output["failedNodes"]|length == 0
       run_once: true

     - name: bgp members status failed
       fail: msg="Device {{item['hostname']}},
                 Why node is in failed state? {{item['reason']}}"
       with_items: "{{json_output['failedNodes']}}"
       run_once: true
