---
- hosts: all
  become: 'yes'
  remote_user: cumulus
  gather_facts: 'no'
  vars:
    ansible_user: "cumulus"
    ansible_ssh_pass: "CumulusLinux!"
    ansible_become_pass: "CumulusLinux!"
  tasks:
    - name: Make a ".ssh" Directory for the Cumulus user
      file: path=/home/cumulus/.ssh state=directory mode=0755

    - name: Copy our Authorized Key to the Cumulus user
      copy: src=/Users/bernd.lehmann/.ssh/id_rsa.pub
            dest=/home/cumulus/.ssh/authorized_keys

    - name: Make a ".ssh" Directory for the Root user
      file: path=/root/.ssh state=directory mode=0755

    - name: Copy our Authorized Key to the Root user
      copy: src=/Users/bernd.lehmann/.ssh/id_rsa.pub
            dest=/root/.ssh/authorized_keys
