---
- hosts: all # Run this against all Hosts in the ansible inventory file
  become: yes           # Becomes the Root user during execution on the remote device
  remote_user: cumulus  # Specifying the Remote User used for SSH
  gather_facts: no      # Don't query the remote node for any identifying information before running tasks
  vars:
    ansible_user: "cumulus"
    ansible_ssh_pass: "CumulusLinux!"
    ansible_become_pass: "CumulusLinux!"
  tasks:                # All of these tasks are executed on the remote device
    - name: Make a ".ssh" Directory for the Cumulus user
      file: path=/home/cumulus/.ssh state=directory mode=0755

    - name: Copy our Authorized Key to the Cumulus user
      copy: src=/Users/bernd.lehmann/.ssh/id_rsa.pub dest=/home/cumulus/.ssh/authorized_keys

    - name: Make a ".ssh" Directory for the Root user
      file: path=/root/.ssh state=directory mode=0755

    - name: Copy our Authorized Key to the Root user
      copy: src=/Users/bernd.lehmann/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys
