---
- include: hostname_set.yml

- hosts: network
  strategy: free

  user: cumulus
  become: 'True'
  gather_facts: 'False'

  handlers:
    - name: reload networking
      command: ifreload -a

    - name: reload quagga
      service: name=quagga state=reloaded

  roles:
    - interfaces
    - quagga
