---
# - include: hostname_set.yml

- hosts: network
  strategy: free

  user: cumulus
  become: 'True'
  gather_facts: 'False'

  handlers:
    - name: reload networking
      command: ifreload -a

    - name: reload frr
      service: name=frr state=reloaded

    - name: restart netq agent
      command: netq config agent restart

  roles:
    - interfaces
    - routing
