---
- hosts: all
  strategy: free

  user: cumulus
  become: True

  handlers:
    - name: reload networking
      command: ifreload -a

    - name: reload quagga
      service: name=quagga state=reloaded

    - name: start quagga
      service: name=quagga state=started

  roles:
    - interfaces
    - quagga
