---

loopback: 10.255.0.5/32

bgp_fabric:
  asn: 65002
  vrf: prod-transit
  router_id: 10.255.0.5
  neighbor:
    - swp51
    - swp52

bgp_networks:
  - 10.255.0.5/32
  - 10.0.1.0/24

peerlink:
  bond_slaves: swp53 swp54
  mtu: 9216
  vlan: 4093
  address: 169.254.1.1/30
  clagd_peer_ip: 169.254.1.2
  clagd_backup_ip: 192.168.100.6
  clagd_sys_mac: 44:38:39:FF:40:93
  clagd_priority: 4096

bridge:
  ports: peerlink
  vids: 101

vlans:
  101:
    alias: Prod-Server-101
    vrf: prod-transit
    vipv4: 10.0.1.254/24
    vmac:  00:00:5e:00:01:01
    pipv4: 10.0.1.252/24
