---

loopback: 10.255.0.10/32

bgp_fabric:
  asn: 65004
  vrf: prod-transit
  router_id: 10.255.0.10
  neighbor:
    - swp51
    - swp52

bgp_networks:
  - 10.255.0.10/32
  - 10.0.3.0/24

peerlink:
  bond_slaves: swp53 swp54
  mtu: 9216
  vlan: 4091
  address: 169.254.1.2/30
  clagd_peer_ip: 169.254.1.1
  clagd_backup_ip: 192.168.100.9
  clagd_sys_mac: 44:38:39:FF:40:91
  clagd_priority: 8192

bridge:
  ports: peerlink
  vids: 103

vlans:
  103:
    alias: Prod-Server-103
    vrf: prod-transit
    vipv4: 10.0.3.254/24
    vmac: 00:00:5e:00:01:03
    pipv4: 10.0.3.253/24
